apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce         # ① one node can mount it read-write at a time. ReadOnlyMany-many pods can mount read-only, ReadWriteMany-many pods can mount read-write, ReadWriteOncePod-single pod 
  resources:
    requests:
      storage: 2Gi          # ② how much storage you need
  # storageClassName:        ③ omitted → uses cluster default. storageClassName: .. to get certain spec