apiVersion: v1
kind: Service
metadata:
  name: postgres-service          # ← this name becomes the hostname
spec:
  selector:
    app: postgres        # routes to any pod with label app=postgres
  ports:
    - port: 5432                  # port the Service exposes
      targetPort: 5432            # port on the pod (can differ)
      protocol: TCP
  type: ClusterIP                 # internal only: 1-ClusterIP, 2-NodePoer exposing to local network (port:30000-32767), 3-LoadBalancer Cloud load balancer with external IP, 4-ExternalName DNS to external hostname